
services:
  db:
    image: postgres:15
    container_name: ledger_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ledger_db
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ledger_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ledger_api_container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/ledger_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
